[package]
name = "geoarrow-test"
version = "0.1.0-dev"
authors = ["Kyle Barron <kylebarron2@gmail.com>"]
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Rust implementation of GeoArrow"
categories = ["science::geo"]
rust-version = { workspace = true }

[dependencies]
geo-traits = { workspace = true }
geo-types = { workspace = true }
geoarrow-array = { workspace = true }
geoarrow-schema = { workspace = true }
wkt = { workspace = true }
